### ISSUE TITLE
Undeliverable mail notification after commenting on a requirement

### ISSUE THREAD

**Issue by fxjordan** [rwth-acis/RequirementsBazaar#126]
I just commented on a requirement at https://requirements-bazaar.org/projects/2/categories/532 and received the following mail at my private RWTH e-mail account, which was addressed to `anonymous@requirements-bazaar.org`
![image](https://user-images.githubusercontent.com/6236455/143435879-2a8ff0e5-2267-448b-989d-ecdbce5396dd.png)

**Comment by fxjordan** [comment]
I suspect the problem is caused by the 'anonymous' user in Requirements Bazaar. It is an actual user (with an entry in the database) and it has the problematic email assigned. 
![image](https://user-images.githubusercontent.com/6236455/162614096-d4f83508-3742-44cf-9628-b81fe7629a60.png)

Now, the question is still: Why is the anonymous user 'following' any project which causes the emails causing the error to be sent?

**Comment by klamma** [comment]
So, if we would remove this user, we would get rid of the problem, right?

**Comment by fxjordan** [comment]
I'm afraid that parts of the code are based on the existence of the anonymous user. So I'd rather check and exclude it from the recipient list in the `EmailDispatcher` class.

**Comment by fxjordan** [comment]
Or even better: There are methods in the `DALFacade` like `dalFacade.getRecipientListForRequirement(...)`. These methods should not return the anonymous user in the first place.

**Comment by fxjordan** [comment]
The problem may be more specific. I only received this error email for notifications on the Requirements Bazaar project. Can you confirm this @klamma

**Comment by klamma** [comment]
Now that you say. True.

**Comment by fxjordan** [comment]
The funny thing is, the code is working fine. I just found out that for some reason the 'anonymous' user is set as project leader for about 120 projects (all with very old creation date in 2015).

**Comment by fxjordan** [comment]
I think there's a nice solution. We can set the `email_lead_subscription` and `email_follow_subscription` subscription attributes of the anonymous user to *false* and this should prevent any emails to be sent to the user.

**Comment by fxjordan** [comment]
Should be fixed. I verified with the Requirements Bazaar project.

**Comment by klamma** [comment]
👍
