### ISSUE TITLE
Wrong links in e-mail notification

### ISSUE THREAD

**Issue by AlexanderNeumann** [rwth-acis/RequirementsBazaar#148]
I receivend an email that a user created a comment and the link was 
https://requirements-bazaar.org/projects/2/categories/2/requirements/3514
but it should be
https://requirements-bazaar.org/projects/2/requirements/3514

**Comment by fxjordan** [comment]
Links should work again soon. I already fixed the code, but found some other problems with email notifications during testing.
I think emails for new categories and projects are never sent because of internal NullPointerExceptions ...
